# Generated by Django 2.2.1 on 2019-08-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Digite seu nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='Insira seu CPF')),
                ('email', models.EmailField(max_length=100, verbose_name='Insira seu email')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataConclusao', models.DateField(verbose_name='Data da conclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=50, verbose_name='Insira o tema do curso')),
                ('assunto', models.CharField(max_length=100, verbose_name='Insira o assunto do curso')),
                ('descricao', models.TextField(verbose_name='Descrição do curso')),
                ('duracao', models.DateField(verbose_name='Duração do curso')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInscricao', models.DateField(verbose_name='Data d insrição')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Digite seu nome completo')),
                ('areaAtuacao', models.CharField(max_length=100, verbose_name='Descreva sua área de atuaçao')),
                ('cpf', models.CharField(max_length=11, verbose_name='Insira seu CPF')),
                ('email', models.EmailField(max_length=100, verbose_name='Insira seu email')),
            ],
        ),
    ]
